---
# Global variables for all hosts

# User configuration
setup_user: samuel
home_dir: "/home/{{ setup_user }}"
setup_repo: "{{ home_dir }}/git/setups/linux-setup"
setup_repo_private: "{{ home_dir }}/git/setups/linux-setup-private"
dotfiles_dir: "{{ setup_repo }}/dotfiles"
configure_grub_windows_first: true

# Basic system packages
basic_packages:
  - tree
  - stow
  - vim
  - build-essential
  - software-properties-common
  - apt-transport-https
  - ca-certificates
  - gnupg

# Networking tools
networking_tools:
  - inetutils-traceroute
  - net-tools
  - nmap
  - curl
  - wget

# VS Code extensions
vscode_extensions:
  - Orta.vscode-jest
  - dbaeumer.vscode-eslint
  - esbenp.prettier-vscode
  - nicoespeon.abracadabra
  - SonarSource.sonarlint-vscode
  - eamodio.gitlens
  - smcpeak.default-keys-windows
  - GitLab.gitlab-workflow
  - pkief.material-icon-theme
  - usernamehw.errorlens
  - ms-python.python
  - ms-python.flake8
  - ms-python.mypy-type-checker

# NVM configuration
# Get the latest version from https://github.com/nvm-sh/nvm?tab=readme-ov-file#installing-and-updating
# Current version: 0.40.1
nvm_version: "0.40.1"

# Node.js versions to install via NVM
node_versions:
  - v22
  - v20
  - v18
  - v16.16.0
  - v10

# Docker configuration
docker_users:
  - "{{ setup_user }}"

# Browsers to install
browsers:
  - google-chrome-stable

