---
- name: Phase 6 - Productivity Tools
  hosts: localhost
  connection: local

  roles:
    - ssh # to be removed
    - obsidian
    # - postman
    # - sqlectron
    # - keepass
    # - libreoffice
    # - okular
    - rclone
    - realvnc
