---
- name: Step 2 - Desktop Environment
  hosts: localhost
  connection: local

  roles:
    - kde
    - safeeyes
    - switch_audios
    - browsers
    - libreoffice
    - okular
    - vlc
    - pinta
    - obs_studio
