---
- name: Step 4 - Work and Productivity Tools
  hosts: localhost
  connection: local

  roles:
    - amqp_tools
    - wifec_vpn
    - kubernetes_tools
    - discord
    - obsidian
    - postman
    - sqlectron
